//***LicenseHere

import PropertyType;
import RPGPropertyType;

////////////////////////////////////////////////////////////////////////////////
//	
//	システム設定のプロパティ定義。
//	ゲーム中に変更可能なプロパティはstatus、変更不能なプロパティはstaticとする。
//	

local settingprops = RPGSystem.settingprops;

local battletypelist = [
	{ val=0, lbl="$T.setting_battletype0", },
	{ val=1, lbl="$T.setting_battletype1", disable=true },	//	未実装・・・
	{ val=2, lbl="$T.setting_battletype2", },
];

//////// basic - 基本システム

settingprops .. {
	part = "basic",
	pid = "battletype",
	lbl = "$T.setting_battletype"
	type = LIST,
	list = battletypelist,
	defval = 0,
};

settingprops .. {
	part = "basic",
	pid = "maxmembers",
	lbl = "$T.setting_maxmembers",
	type = SCALAR
	range = (1,6)
	defval = 4,
	refresh = 1,
};

settingprops .. {
	part = "basic",
	pid = "maxlv",
	lbl = "$T.MAXLV",
	type = SCALAR
	range = (1,999)
	defval = 99,
};

settingprops .. {
	part = "basic",
	proptype = "status",
	pid = "walkspd",
	lbl = "$T.setting_walkspd",
	type = SCALAR,
	ui = "bar",
	range = (0.0,10.0),
	q = 10
	defval = 5.0,
};

settingprops .. {
	part = "basic",
	proptype = "status",
	pid = "jumph",
	lbl = "$T.setting_jumph",
	type = SCALAR,
	ui = "bar",
	range = (0.0,10.0),
	q = 10
	defval = 2.0,
};

settingprops .. {
	part = "basic",
	pid = "jxptype",
	lbl = "$T.setting_jxptype",
	type = LIST,
	list = [
		{ lbl="$T.setting_jxptype_auto", val=0, }
		{ lbl="$T.setting_jxptype_manual", val=1, }
	]
	defval = 0,
};

settingprops .. {
	part = "basic",
	proptype = "status",
	pid = "hotelheal",
	lbl = "$T.setting_hotelheal",
	type = LIST,
	list = [
		{ lbl="$T.setting_hotelheal0", val=0, }
		{ lbl="$T.setting_hotelheal1", val=1, }
		{ lbl="$T.setting_hotelheal2", val=2, }
	]
	defval = 2,
};

settingprops .. {
	part = "basic",
	proptype = "status",
	pid = "lvupheal",
	lbl = "$T.setting_lvupheal",
	type = BOOL,
	defval = false,
};

settingprops .. {
	part = "basic",
	proptype = "status",
	pid = "showhidden",
	lbl = "$T.setting_showhidden",
	type = BOOL,
	type = LIST,
	list = [
		{ lbl="$T.lbl_none", val=0, }
		{ lbl="$T.lbl_auto", val=1, }
		{ lbl="$T.lbl_always", val=2, }
	]
	defval = 1,
};

//////// command - バトルコマンド

for( local l = 0;l < 8;l ++){
	settingprops .. {
		part = "command",
		pid = "battlecmd"..l,
		proptype = "status",			//	イベントコマンドで置き換えられたりすると便利？
		lbl = "${T.lbl_command}"..l
		type = LIST,
		list = RPGProperties.battlecmdlist,
		defval = null,
	};
}

//////// 

settingprops .. {
	part = "startup"
	pid = "inimembers"
	lbl = "$T.setting_inimembers"

	type = DATAIDS
	datalist = @() array( ::skstudio.editor["data"]["maxmembers"] ?? ::conf.setting.maxmembers).map(
		@( _, i){
			return {
				head = ""..i,
				datatype = ["player"],
				nullable = true
			}
		}
	)
	defval = ["P000"]
};

settingprops .. {
	part = "startup"
	pid = "inimoney"
	lbl = "$T.mymoney"

	type = SCALAR
	range = (0, 1000000)

	defval = 100
};

settingprops .. {
	part = "startup"
	pid = "titlemap"
	lbl = "$T.setting_titlemap"
	type = DATAID
	datatype = ["map"]
	
	defval = "M001"
};


settingprops .. {
	part = "startup"
	pid = "inimap"
	lbl = "$T.setting_inimap"
	type = CUSTOMBUTTON

	tostring = @( v){
		local dirs = ["↑","→","↓","←",];
		local map = ::conf.map[v["mapid"]], pos = v.pos, r = (Math.iround( pos[4]*Math.RTOD)/90) & 3;
		local lbl = sprintf( "%S: %S (%S %S %S %S)", v["mapid"], map["name"] || "$T.lbl_invalidid", pos[0], pos[1], pos[2], dirs[r]);
		return lbl;
	}

	//	コンテキストメニュー表示してマップ編集に移動
	edit = @( val){
		if( MenuPopup.run( [{ lbl="$T.setting_inimap_open", icon="\ue89e" }], view.findChild( "btn"))){
			::skstudio.openEditor( "/.x/map/%S" % val.mapid);
			local pos = val["pos"];
			if( pos){
				::skstudio.editor.canvas.camwork.moveFocus( Vector3D( pos), 0);
			}
		}
	}
};

//////// メニュー画面設定。

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_status",
	lbl = @() (T.format_view % T.status),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_item",
	lbl = @() (T.format_view % T.item),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_skill",
	lbl = @() (T.format_view % T.skill),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_equip",
	lbl = @() (T.format_view % T.equip),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_job",
	lbl = @() (T.format_view % T.job),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_formation",
	lbl = @() (T.format_view % T.formation),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_save",
	lbl = @() (T.format_view % T.save),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_load",
	lbl = @() (T.format_view % T.load),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 0
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_config",
	lbl = @() (T.format_view % T.config),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

settingprops .. {
	part = "ui",
	proptype = "status",
	pid = "menu_exitgame",
	lbl = @() (T.format_view % T.exitgame),
	type = LIST,
	list = RPGProperties.uivisiblelist,
	defval = 3
};

////////////////////////////////////////////////////////////////////////////////
//	ステージ設定
//	以下のプロパティはステージの保存時に保存される。また、mapedit=trueの場合はマップエディタで初期設定を設定可能。
//	これらの状態変更は、イベントコマンド「ステージ設定の変更」で行う。BGM変更みたいなのは個別にコマンドがある

local rendersetlist(){
	local a = [];
	foreach( v in ::RenderSettings.data){
		if( v.renderpass == 2) a .. { lbl=v.name, id=v.id, icon="\ue430", val=v.id }	//	deferredのみ
	}
	return a;
}

local stageprops = RPGSystem.stageprops;

stageprops .. { mapedit=true, pid="encntrate", lbl="$T.lbl_encntrate", type=SCALAR, ui="bar", range=(0.0,100.0), q=10, barrange=(0.0,100.0,1.0), defval=0.0 };

stageprops .. {
	mapedit=true,
	pid="rsetid",
	lbl="$T.menu_view_rendersetting",
	type=LIST,
	list = rendersetlist,
	defval="pbr_df",

	func = @( stage, val){
		stage.changeRenderSetting( val);
	}
	
	hover = @( val){
		local ed = ::skstudio.editor;
		if( val){
			local rsetid = val.id;
			ed.canvas.view.renderer.setEnvironment( ::RenderSettings.getEnvironment( rsetid));
		}else{
			local rsetid = ed.canvas.envmenu.selitem.id;
			ed.canvas.setRenderSettingID( rsetid);
		}
	}
};

local bgtypelist = [
	{ lbl="$T.lbl_skybox", val="skybox", icon="\ue3c4", }
	{ lbl="$T.sfxbit_0", val="col", icon="\ueb36", }
	{ lbl="$T.lbl_gradation", val="grad", icon="\ue3e9", }
	{ lbl="$T.lbl_texture", val="tex", icon="\ue3d3"}
];

local bgpropdef(){
	return {
		name = "$T.lbl_bgimage"
		props = @( v){
			local a = [
				{ pid="type", lbl="$T.lbl_type", type=LIST, list = bgtypelist, refresh = true},
			];
			switch( v["type"]){
			case "col":
				a .. { pid="col", lbl="$T.sfxbit_0", type=RGB, defval=(v["col"]||0x000000ff), };
				break;
			case "grad":
				a .. { pid="grad", lbl="$T.lbl_gradation", type=3312, defval={color=[0x000033ff, 0x0000ffff]} };
				break;
			case "tex":
				a .. { pid="tex", lbl="$T.lbl_texture", type=PATH, defval="", };
				a .. { pid="uv", lbl="$T.lbl_uv", type=LIST, defval="", };	//	Cylinder, Equirectangular, Cube
				break;
			}
			return a;
		}
		setprop = @( prop, data, val){
			local ed = ::skstudio.editor;
			if( (ed instanceof MapEditor) && !ed.modaledit){	//	u-m
				ed.canvas.setBackground( data);
			}
		}
		tostring = @( v){
			local ts = bgtypelist.find( @( x) x.val==v.type)["lbl"];
			switch( v.type){
			case "col":
				local cs = "%06x" % (v["col"]>>>8);
				ts = rtf( `$ts: [#$cs]■`);
				break;
			case "grad":
				local g = v["grad"]["color"]||[0xff0000ff];
				local cs0 = "%06x" % (g[0]>>>8);
				local cs1 = "%06x" % (g.last()>>>8);
				ts = rtf( `$ts: [#$cs0]■[#$cs1]■`);
				break;
			}
			return ts;
		}
	};
}

//	黒、スカイボックス、-、色指定、　テクスチャ指定
stageprops .. {
	mapedit=true,
	pid="bg",
	lbl="$T.lbl_bgimage",
	type=PROPERTYLIST,
	defval={ type="skybox", },
	propdef = bgpropdef

	func = @( stage, val){
		stage.view3d.renderer.bgpass = stage.createBackground( val);
	}
};

local weatherpropdef(){
	local idmap = {}, idlist = [];
	foreach( i, v in ::weatherlist){
		if( v.type) idmap[v.id] <- v;
		idlist .. { lbl="$T.weather_"..v.id, icon="\uf1ad", val=v.id, }
	}
	return {
		name = "$T.setting_weather"
		props = @( v){
			local a = [
				{ pid="id", lbl="$T.lbl_type", type=LIST, list=idlist, refresh=true,
					set = @( prop, data, val){
						Table.clear( data) ... idmap[val];
					}
				},
			];
			local cls = SK3DWeathers[v["type"]], props = cls["props"];
			a ... props;
			return a;
		}
		setprop = @( prop, data, val){
			local ed = ::skstudio.editor;
			if( (ed instanceof MapEditor) && !ed.modaledit){	//	u-m
				ed.canvas.refreshLinkedWeather( data);
			}
		}
		edit = @( data){
			local ed = ::skstudio.editor;
			local skychk = ed.canvas.skychk.isSelected();
			ed.canvas.skychk.setSelected( true);
			ed.canvas.refreshLinkedWeather( data);
			local ret = PropertyEditPopup.run( null, this, data);
			if( !skychk){
				ed.canvas.refreshLinkedWeather( null);
				ed.canvas.skychk.setSelected( skychk);
			}
			return ret;
		}
		tostring = @( v) v["id"] ? sprintf( "$T.weather_%S", v["id"]) : "$T.lbl_none"
	};
}

stageprops .. {
	mapedit=true,
	pid="mapshotmode",
	lbl="$T.lbl_mapshotmode",
	type=LIST,
	list=["$T.uivisible0","$T.uivisible3","$T.lbl_automapping"]
	defval = 0
}

stageprops .. {
	mapedit=true,
	pid="weather",
	lbl="$T.setting_weather",
	type = PROPERTYLIST,
	propdef = weatherpropdef,
	defval = {type=null},

	func = @( stage, val){
		stage.view3d.renderer.fadeWeather( val, 500);
	}
};

stageprops .. {
	mapedit=true, pid="bgmid", lbl="$T.lbl_bgm", type=RESID, restype = ["bgm"], defval=null
}

stageprops .. {
	mapedit=true, pid="reverbid", lbl="$T.reverb", type=LIST,
	list=@() ::conf._resource.snd._env.reverbs.map( @( v)({ lbl="$T.reverb_"..v.id, icon="\ue049", val=v.id, })),
	defval="PLAIN"

	func = @( stage, val){
		stage.scn.sk3dsound.setReverbID( val);
	}
};

stageprops .. {
	pid = "playervisible"
	lbl = "$T.setting_playervisible"
	type = BOOL
	defval = true

	func = @( stage, val){
		stage.setPlayerVisible( val);
	}
};

stageprops .. {
	pid = "playermodel"
	lbl = "$T.setting_playermodel"
	type = DATAID
	datatype = ["player"]
	defval = null	//	null=先頭

	func = @( stage, val){
		stage.changePlayer3D( val);
	}
};

stageprops .. {
	pid = "ctrmode",
	lbl = "$T.setting_ctrmode",
	type = LIST,
	list = [
		{ lbl="$T.ctrmode0", val=0 },
		{ lbl="$T.ctrmode1", val=1 },
		{ lbl="$T.ctrmode2", val=2 },
		{ lbl="$T.ctrmode3", val=3 },
	]
	defval = 1,
};

stageprops .. {
	pid = "menuopenable",
	lbl = "$T.setting_menuopenable",
	type = BOOL,
	defval = true,
};

stageprops .. {
	pid = "saveable",
	lbl = "$T.setting_saveable",
	type = BOOL,
	defval = true,
};

local destprop = { pid="dest", lbl = "$T.cmd_mapmove_dest", type=PORTAL, cnt="cnt6v.ui" };
local exitmappropdef = {
	name = "$T.setting_exitmap"
	props = @( v){
		local a = [
			{ pid="enabled", lbl="$T.lbl_enabled", type=BOOL, refresh=true,
				get = @( prop, data) !!data["dest"],
				set = @( prop, data, val){
					local m = ::conf.setting.inimap, p = m.pos;
					data.dest <- val ? { mapid=m.mapid, pos=p } : null;
				}
			},
		];
		if( v["dest"]) a .. destprop
		return a;
	}
	tostring = @( v){
		if( !v["dest"]){
			return "$T.lbl_notset";
		}else{
			return getPropertyText( destprop, v);
		}
	}
}

stageprops .. {
	mapedit=true, pid="exitmap", lbl="$T.setting_exitmap", type=PROPERTYLIST,
	propdef = exitmappropdef,
	defval = {dest=null},
}

stageprops .. {
	pid = "mapexitable",
	lbl = "$T.setting_mapexitable",
	type = BOOL,
	defval = true,
};

stageprops .. {
	mapedit=true, pid="canenter_water", lbl="$T.setting_canenter_water", type=BOOL//1, cnt="cnt5.ui",
	defval = false,
	
	func = @( stage, val){
		local bci = stage.bwcol.ref, t = stage.stat.statmap;
		local b = 1 | (t["canenter_water"]?0:2) | (t["canenter_hole"]?0:4);
		bci.setFinMode( b);		//	barrior | water | hole
	}
}

stageprops .. {
	mapedit=true, pid="canenter_hole", lbl="$T.setting_canenter_hole", type=BOOL//1, cnt="cnt5.ui",
	defval = false,
	
	func = @( stage, val){
		local bci = stage.bwcol.ref, t = stage.stat.statmap;
		local b = 1 | (t["canenter_water"]?0:2) | (t["canenter_hole"]?0:4);
		bci.setFinMode( b);		//	barrior | water | hole
	}
}

////////////////////////////////////////////////////////////////////////////////
//	コンフィグ設定
//	


