import VirtualKeyCode;
import ModifiersMask;

////////////////////////////////////////////////////////////////////////////////
//	
//	デバッグオプション
//	・全アイテムの所持、お金MAX
//	・全スキル、全ジョブ使用可
//	・キャラのレベル強制(1~99)
//	・壁すり抜け
//	・不死身モード
//	・言語の選択
//	
//	言語以外はデバッグ中のデバッグメニューからも使える。
//	
//	あと、マップエディタからのデバッグ起動で、指定したマップからの開始も出来る。更に指定したイベントの即時実行。キャラはそのイベントの真ん前に移動。
//	
//	
//	ツールからゲームに以下の操作が可能
//	- 一時停止・再開
//	- デバッグメニューの表示
//	- ホットリロードもどき。バトル中以外の状態は保存してゲーム再起動。
//	- マクロ実行など便利な操作
//	- 任意のスクリプト実行
//	- MCPコマンドの中継。コントロール操作なども可能。
//	
//	これらの機能を使うために、ゲーム側にIPCConnectionをバインドする必要がある。
//	
//	

local showDebugMenu( btn){
	local st = ::skstudio;
	local menudata = [
		st.getMenu( "menu_debug_stop"),
		st.getMenu( "menu_debug_pause"),
		st.getMenu( "menu_debug_start"),
		st.getMenu( "menu_debug_restart"),
		"-",
		st.getMenu( "menu_debug_selectslot"),
		st.getMenu( "menu_debug_setting"),
	]
	local m = MenuPopup.run( menudata, btn);
	if( m){
		st.execMenu( m);
	}
}

//	setting activity
local activity = {
	uid="act_debug",
	place="bottom",
	order=70,
	icon="\uf06a",
	badge=null,
	tips="$T.act_debug"
	slbl="$T.lbl_debug"
	
	func = showDebugMenu,
}

::debugsession <- null;	//	現在のデバッグセッション。nullならデバッグ中ではない。

local updateActivity(){
	// activity.icon = ::debugsession ? ("\uf06a",0xff9900ff) : "\uf06a";
	activity.badge = ::debugsession ? (::debugsession.paused ? ("\ue034",0xff7700ff) : ("\uef4a",0x0077ffff)) : null,
	::skstudio.refreshActivity( "act_debug");	//	アクティビティの状態を更新
}

//	セーブ場所は固定
local _savedir = FileRef( skGetCurrentDir().."/savedata"); _savedir.mkdirs();
if( !("saveslotidx" in ::workspace)) ::workspace.saveslotidx <- -1;

local selectSaveSlotMenu( m){
	::workspace.saveslotidx <- m.saveslot;
}

local clearSaveData( m){
	if( Dialogs.confirm( {msg="$T.confirm_clearsavedata"})){
		foreach( f in _savedir.getList( "*.bin")){
			f.deleteFile();
		}
	}
}

//	workingdataは、confとresourceのデータがある
//	editor.getWorkingData()で取得する
local gatherWorkingData(){
	local wd = { conf={}, res={}};
	foreach( path, e in ::skstudio.tabeditors){
		if( e.isFileChanged() && e["getWorkingData"]){
			local d = e.getWorkingData();
			override( wd, d, true);
		}
	}
	return wd;
}

//	startDebugMenu, restartDebugMenu
local getDebugArgs( m){
	local args = [];
	local slotidx = m["slot"]??::workspace.saveslotidx??-1;
	args .. "-slot" .. slotidx;
	local lang = m["lang"]??::workspace["debuglang"];
	if( lang) args .. "-lang" .. lang;
	local debugtouch = m["debugtouch"]??::workspace["debugtouch"];
	if( debugtouch) args .. "-debugtouch";
	local debuglv = int( m["debuglv"]??::workspace["debuglv"]);
	if( debuglv > 0) args .. "-debuglv" .. debuglv;
	local debugitems = m["debugitems"]??::workspace["debugitems"];
	if( debugitems) args .. "-debugitems";
	//	
	local wd = gatherWorkingData();
	if( wd){
		local bb = ObjectOutput.encode( wd);
		local tmpdir = FileRef( "tmp");
		local wdfile = FileRef( tmpdir, "wd.ser");
		wdfile.save( bb);
		args ... ["-wd", wdfile.path];
	}
	return args;
}

//	デバッグを開始。タイトルから、選択したセーブから。。。
//	既にデバッグが開始されている場合は、デバッグ中のゲームを終了して再起動する。
//	
function startDebugMenu( m){
	if( ::debugsession){
		return ::debugsession.setPaused( false);
	}
	local args;
	local slotidx = m["slot"]??::workspace.saveslotidx;
	switch( m["uid"]){
	case "menu_debug_start":
		args = ["-recfx"];	//	-recfx:使用したシェーダーを記録。
		break;
	case "menu_debug_here":
		args = ["-map", m.mapid,  encodeJSON( m.pos)];
		break;
	case "menu_debug_battle":
		args = ["-battle", m.mapid, m.gid];
		if( m["skillid"]) args .. "-skill" .. m.skillid;
		if( m["enemyid"]) args .. "-enemy" .. m.enemyid;
		break;
	case "menu_debug_event":
		args = ["-event", m.mapid, m.evid, m.evpage];
		break;
	}
	args ... getDebugArgs( m);
	//	
	local exe = FileRef( "rpgcobo.exe");
	local p = popen_s();
	p.open( exe, ["-testplay", ...args], 0x100);
	local sess = DebugSession();
	newthread().start( @(){
		sess.connect( p, 30);	//	成功したら::debugsessionにセットされる。失敗したらnullのまま。
	}, this);
	local ret = Dialogs.showWaiting( "$T.lbl_debug_connecting", @(){
		return (::debugsession == sess || !sess.isrunning()) ? false : true;
	}, true);
	if( !ret){
		sess.finish();
	}
	return ::debugsession;
}

local stopDebugMenu( m){
	if( ::debugsession){
		::debugsession.finish();
	}
}


//	開始したデバッグプロセスを監視したり、IPCConnectionを通じてコマンドを実行する。
//	
class DebugSession
{
	ipc = null;			//	IPCConnection
	popen = null;		//	popen_s
	thread = null;		//	watch dog
	paused = false;		//	ゲームが一時停止中かどうか。pauseChanged()で通知される。
	debugbar = null;	//	SKView : デバッグバー
	
	//	popen_sで開始したデバッグプロセスに接続する。失敗したらfalseを返す。
	function connect( p, trynum=6){
		try{
			popen = p;
			(thread = newthread( "debug session")).start( run, this);
			ipc = IPCConnection();
			ipc.bind();
			local b = false;
			for( local l = 0;l < trynum;l ++){
				sleep( 200);
				try{
					printf( "IPCConnection connecting...\n");
					if( b=ipc.connect( popen.processid())) break;
				}catch( ex){
				}
			}
			if( !b) throw Exception( "Failed to connect to debug process.");
			printf( "DebugSession connected to debug process %S.\n", popen.processid());
			::debugsession = this;
			::rootview.addEventListener( BROADCAST_EVENT, sessionevent);
			::skstudio.titlebar.showDebugBar( true);
			debugbar = ::skstudio.titlebar.debugbar;
			debugbar.addEventListener( ACTION_EVENT, sessionevent);
			pauseChanged( false);
			return true;
		}catch( ex){
			printexception( ex);
			finish();
			return false;
		}
	}
	
	//	
	function finish(){
		if( popen){
			popen.kill();
			printLines();
			popen.close();
			popen = null;
		}
		ipc?.unbind();
		ipc = null;
		::debugsession = null;
		updateActivity();
		::rootview.removeEventListener( BROADCAST_EVENT, sessionevent);
		::skstudio.titlebar.showDebugBar( false);
		debugbar?.removeEventListener( ACTION_EVENT, sessionevent);
	}

	//	
	function isrunning(){
		return popen?.isrunning();
	}

	//	
	function run(){
		while( popen?.isrunning()){
			printLines();
			suspend();
		}
		finish();
		thread = null;
	}

	//	
	function sessionevent( e){
		printf( "DebugSession sessionevent: %S %S\n", e.id, encodeJSON( e["actioncmd"]));
		switch( e.id){
		case BROADCAST:
			local bc = e["actioncmd"];
			if( bc["cmd"] == "dir_refreshed"){
				local p = bc.dir.path;
				printf( "Directory refreshed: %S\n", p);
				if( p.startsWith( "/.x/")){	//	データが更新されたら、デバッグ中のゲームに通知する
					triggerHotReload();
				}
			}
			break;
		case ACTION_PERFORMED:
			switch( e.src["name"]){
			case "dbg_pause":
				setPaused( true);
				break;
			case "dbg_go":
				setPaused( false);
				break;
			case "dbg_stop":
				finish();
				break;
			case "dbg_restart":
				restartDebug();
				break;
			}
			break;
		}
	}

	//	
	function printLines(){
		for( local li; li = popen.readLine();){
			printf( "::: %S\n", li.trim());
		}
	}

	///////////////////////////////////////////////////////////////////
	//
	//	コマンド

	function triggerHotReload(){
		local wd = gatherWorkingData();
		local wdpath = null;
		if( wd){
			local bb = ObjectOutput.encode( wd);
			local tmpdir = FileRef( "tmp");
			local wdfile = FileRef( tmpdir, "hotreload.ser");
			wdfile.save( bb);
			wdpath = wdfile.path;
		}
		return ipc.invokeIPCScript( "return ::hotReload( %S);" % encodeJSON( wdpath), 0);	//	notify
	}
	
	//	デバッグ中のゲームを一時停止する。再開するにはsetPaused(false)を呼ぶ。
	//	ゲームのポーズは完全な処理中断ではなく、ループは回っているがメイン処理が止まっている状態。でないとコマンドが届かなくなる。
	//	※ポーズされるとpauseChanged( b)が呼ばれる。
	function setPaused( b){
		return ipc.invokeIPCScript( "return ::RPGMain.setPaused( %S);" % b, 0);	//	notify
	}

	//	デバッグ中のゲームをホットリロードや再起動する。
	function restartDebug(){
		local wd = gatherWorkingData();
		if( wd){
			local bb = ObjectOutput.encode( wd);
			local tmpdir = FileRef( "tmp");
			local wdfile = FileRef( tmpdir, "wd.ser");
			wdfile.save( bb);
		}
		local b = ipc.invokeIPCScript( "return ::restartDebug();");
		newthread().start( @(){
			//	もう一度接続が必要。ある程度時間がかかるので別スレッド化
			local b = false;
			for( local l = 0;l < 6;l ++){
				sleep( 200);
				try{
					printf( "IPCConnection connecting...\n");
					if( b=ipc.connect( popen.processid())) break;
				}catch( ex){
				}
			}
			if( !b){
				finish();
				throw Exception( "Failed to connect to debug process.");
			}
		}, this);
	}

	function switchToDebugWindow(){
		return ipc.invokeIPCScript( "skMoveScreen( { flags=MoveScreenFlags.MOVESCREEN_FRONT });", 0);
	}

	///////////////////////////////////////////////////////////////////
	//	デバッグプロセスから呼ばれる

	function pauseChanged( p){
		paused = p;
		debugbar.findChild( "dbg_pause").setEnabled( !p);
		debugbar.findChild( "dbg_go").setEnabled( !!p);
		updateActivity();
	}
}


//////////////////////////////////////////////////////////////////////////////////////////
//
//	不具合報告機能。ログ又はプロジェクト全体をzipにしてcloudflareにアップロードする。
//	やり取りはDiscordに誘導する。
//	- 不具合の内容を書くダイアログを表示。
//	- フォーム送信 POST https://user.rpg-cobo.com/api/report_problem
//		⇒ アップロード用のURLが来るのでそこにPUT。
//	

class ReportProblemDialog extends UndoableDialog
{
	comedit = null;
	zipg = null;
	
	zipfile = null;
	zipthread = null;
	
	constructor( v){
		super( v);
		zipg = view.findChild( "zipg");
		zipg.setVisible( false);
		view.setValue( "msg", "$T.lbl_build_zipping");
		comedit = view.findChild( "edit");
		view.setValue( "title", rtf( "不具合を報告してプロジェクトをアップロードする"));
	}

	function refresh(){
	}

	function shown(){
		local g = zipg, rlbl = zipg.findChild( "rlbl");
		local prgptr = ptr( 0.0);
		local prgfunc( p, s){
			if( p > ~prgptr+0.02 || (p>=1.0 && ~prgptr<1.0)){
				g.anime( p>=2.0 ? 12 : p>=1.0 ? 11 : p*10.0);
				rlbl.setText( s);
				prgptr << p;
				suspend();
			}
		}
		zipg.setVisible( true);
		zipthread = newthread();
		zipthread.start( @(){
			::skstudio.freezeEditorView( true);	//	editorの再描画を抑制して並列処理を高速化
			startZip( prgfunc);
			::skstudio.freezeEditorView( false);
		}, this);
	}

	//	
	function startZip( prgfunc){
		prgfunc( 0.0, "");
		local t0 = skGetTime();
		local srcdir = FileRef( ".");
		//	zipするファイルを集める
		local ziplist = [];
		local visitfile( f, chkfn){
			if( chkfn( f)){
				local fn = f.name;
				if( f.isDirectory()){
					foreach( cf in f.getList()) visitfile( cf, chkfn);
				}else{
					ziplist .. f;
				}
			}
		}
		//	完全な形でアップロードするために、backup, build等の排除可能なもの以外は全て入れる
		local skipmap = { ".git"=1, "backup"=1, "build"=1, "private"=1, "tmp"=1, "docs"=1, "work"=1,};
		foreach( f in srcdir.getList()) visitfile( f, @( f) !skipmap[f.name]);
		//	
		local num = length( ziplist), size = 0;
		local bb = ziplist.reduce( @( f, bb){
			bb.putt( f.path); bb.puti( f.size); bb.putl( f.lastmodified); return bb;
		}, ByteBuffer());
		bb.pos = 0;
		zipfile = FileRef( "tmp/uploading.zip");
		local hash = bb.hashcode();
		if( zipfile.exists() && ::buildziphash == hash){
			printf( "HASH ONAJI! %S\n", hash);
			size = zipfile.size;
			goto SKIP;
		}
		//
		//	zip実行。6並列で高速化
		local zip = ZipWriter( zipfile);
		local fa = [];
		for( local l = 0;l < num;l ++){
			local f = ziplist[l];
			fa .. (f, ::getRelativePath( srcdir.path, f.path));
			if( length( fa)>=6 || l==num-1){
				size += zip.writeLocalFilesAtOnce( fa);
				fa.clear();
				prgfunc( l * 1.0 / num, sizestr( size));
			}
		}
		zip.writeCentral();
		zip.close();
		zipfile.refresh();
		printf( "ZIPPED TIME=%S\n", skGetTime( t0));
		::buildziphash = hash;
	SKIP:
		prgfunc( 1.0, sizestr( size));
		view.findChild( "rung").anime( 1);
	}

	function actionevent( e){
		switch( e.src["name"]){
		case "btn_run":
		{
			if( !Dialogs.confirm( {msg=rtf( "$T.confirm_report_problem"), icon="\ue2c3"})) break;
			doUpload();
			break;
		}
		case "btn_discord":
			::account.openWeb({ page="discord", });
			break;
		}
		super.actionevent( e);
	}

	function getProjectVer(){
		local f = FileRef( "rpgcobo.ver");
		if( f.exists()){
			try{
				local t = decodeJSON( f.load());
				return t.tag;
			}catch( ex){}
		}
		return null;
	}

	function doUpload(){
		local params = {
			token = ::account.token,
			zipsize = int( zipfile.size),
			comment = comedit.getText(),
			tag = getProjectVer(),
		};
		try{
			local r = ::account.requestAPI( {api="report_problem", method="POST", params=params});
			printf( "report_problem params=%S result=%S\n", encodeJSON( params, 5), encodeJSON( r, 5));
			if( r.result != "OK"){
				Popups.showError( "$T.lbl_uploading_project_error: "..r.error);
				return;
			}
			//	http PUT
			local self = this;
			local putproj( prgfunc){
				local http = HTTPClient();
				http.listener = @( h, id, arg){
					switch( id){
					case "send":
						local w = arg.w * 1.0 / arg.size;
						prgfunc( w);
						break;
					}
				}
				http.verbose = true;
				http.addHeader( "Content-Type", "application/zip");
				http.put( r.puturl, HTTPFileSender( self.zipfile));
				prgfunc( 1.0);
				ContestPopup.statcache <- null;	//	キャッシュクリア
				return true;
			}
			//	プログレス表示
			local ret = Dialogs.progress( "$T.lbl_uploading_project", putproj, false);	//	キャンセル不可
			if( ret instanceof Exception){
				Popups.showError( "$T.lbl_uploading_project_error");
			}else{
				Popups.showInfo( "$T.lbl_uploading_report_done");
				//	自分も消しちゃう
				close();
			}
		}catch( ex){
			printexception( ex);
			Popups.showError( "$T.lbl_uploading_project_error");
		}
	}

	function checkCancel( c){
		if( c == VK_ENTER) return true;	//	enterで始まらんように
		return super.checkCancel( c);
	}

	static function run(){
		local dlg = this( "/plugin/rpgtools/common/ui/reportdialog.ui");
		dlg.show();
	}
}



/////////////////////////////////////////////

with( ::skstudio){
	registerActivity( activity);
	registerMenu( { uid="menu_debug", lbl="$T.menu_debug", isdir=true, submenu=[]});
	registerMenu( { uid="menu_debug_stop", parentid="menu_debug", lbl="$T.menu_debug_stop", icon="\uef71", defkey="_F5", func=stopDebugMenu, hide=@() !::debugsession });
	registerMenu( { uid="menu_debug_pause", parentid="menu_debug", lbl="$T.menu_debug_pause", icon="\ue034", defkey="F4", func=@() ::debugsession.setPaused( true), hide=@() !::debugsession, disable=@() ::debugsession["paused"] });
	registerMenu( { uid="menu_debug_start", parentid="menu_debug", lbl=@()::debugsession?"$T.menu_debug_resume":"$T.menu_debug_start", icon="\uf06a", defkey="F5", func=startDebugMenu, disable=@() !!::debugsession && !::debugsession["paused"] });
	registerMenu( { uid="menu_debug_restart", parentid="menu_debug", lbl="$T.menu_debug_restart", icon="\ue5d5", defkey="^F5", func=@() ::debugsession.restartDebug(), hide=@() !::debugsession });
	registerMenu( { uid="menu_debug_switch", parentid="menu_debug", lbl="$T.menu_debug_switch", icon="\uef43", defkey="^Enter", func=@() ::debugsession.switchToDebugWindow(), hide=@() !::debugsession });
	registerMenu( { parentid="menu_debug", separator="*1"});
	registerMenu( { uid="menu_debug_selectslot", parentid="menu_debug", lbl="$T.menu_debug_selectslot", submenu=@(){
		return (_savedir.getList( "save???.bin").map( @( f){
			local selidx = ::workspace["saveslotidx"];
			local idx = int( f.name.substring( 4, 7));
			return { lbl="${T.lbl_slot}"..idx, saveslot=idx, icon=(idx==selidx?"\ue5ca":""), func=selectSaveSlotMenu };
		}) .. {
			lbl="$T.newgame", saveslot=-1, icon=(-1==::workspace["saveslotidx"]?"\ue5ca":""), func=selectSaveSlotMenu
		} .. {
			lbl="$T.menu_debug_title", saveslot=-2, icon=(-2==::workspace["saveslotidx"]?"\ue5ca":""), func=selectSaveSlotMenu
		}).sort( @( v) v.saveslot) .. "-" .. {
			lbl="$T.menu_debug_clearsavedata", icon="\ue0b8", func=clearSaveData, 
		};
	}});
	registerMenu( { uid="menu_debug_setting", parentid="menu_debug", lbl="$T.menu_debug_setting", icon="\ue8b8", func = @( m){ PreferenceDialog.run( "debug"); } });

	//	ここでヘルプ追加しちゃお
	registerMenu( { uid="menu_help", lbl="$T.menu_help", isdir=true, submenu=[]});
	registerMenu( { uid="menu_help_guide", parentid="menu_help", lbl="$T.menu_help_guide", icon="\ue051", func=@( m){
		skOpenURL( "https://rpg-cobo.com/guides/start");
	}});
	registerMenu( { parentid="menu_help", separator="*1"});
	registerMenu( { uid="menu_help_report", parentid="menu_help", lbl="$T.menu_help_report", icon="\ue868", func=@( m){
		ReportProblemDialog.run();
	}});
	// registerMenu( { parentid="menu_help", separator="*1"});
	// registerMenu( { uid="menu_help_editor", parentid="menu_help", lbl="UIエディタ のマニュアル", icon="\uf1c0", defkey="F1" });
}

module.hookAction( "editor_closing", @(){
	stopDebugMenu( null);
}, 100);
