import VirtualKeyCode;
import ModifiersMask;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//	
//	gltf対応のためにPMEditorを強化。
//	- 複数メッシュのサポートのため、PolygonMeshTreeを使用。それに伴いPMEditorも複数メッシュの編集を可能に。
//	- gltfはツールで読み込み、PolygonMeshTree(pmt)に変換される。
//	- PMEditorは .pm, .pmt を読み込み可能。.pmは内部でpmtに変換され、書き出す際にpm形式で保存される。
//	- PMEditorは .gltf, .glb の読み込みは不可。必ずpmt変換を通して開く。
//	- マテリアルの編集はあまり変更の必要はなし。パーツ・シェイプ編集では選択されているpmtノード(SK3DObject)が対象になり、ボーンツリーなどはpmtノードのものになる。
//	- 
//	

class PMEditor extends EditorViewBase
{
	res = null;				//	Resource : 
	
	pmt = null;				//	PolygonMeshTree : 編集対象のメッシュツリー。.pmを読み込んでもpmtになる
	//	view
	canvas = null;			//	PMCanvas : プレビューキャンバス
	rightpanel = null;		//	RightPanel : 
	timeline = null;		//	TimelineBarBehavior : タイムライン
	
	static function createEditor( path){
		if( !path.endsWith( ".pm") && !path.endsWith( ".pmt") && !path.endsWith( ".gltf") && !path.endsWith( ".glb")) return null;
		//	
		local ed = ::loadSKView( "/skstudio/ui/pmeditor/pmeditor.ui", PMEditor);
		ed.init( path);
		return ed;
	}
	
	function init( path){
		op = OperationStack();
		canvas = PMCanvas( this);
		rightpanel = PMRightPanel( findChild( "right"), this);
		timeline = TimelineBarBehavior( findChild( "timeline"));
		timeline.view.addEventListener( VALUE_EVENT, timeevent);
		openResource( ::getResource( path));
	}
	
	function openResource( r){
		res = r;
		r.userdata = null;
		//	データセット
		if( r.name.endsWith( ".pm")){
			pmt = pmToPMT( r);
		}else
		if( r.name.endsWith( ".pmt")){
			pmt = r.getContent();
		}else
		if( r.name.endsWith( ".gltf") || r.name.endsWith( ".glb")){
			local loader = GLTFLoader();
			pmt = loader.loadGLTF( r.loadData());
		}
		setPolygonMeshTree( pmt);
		
		/////////////////////////////////////////////////////
		local editinfo = null;//editable && pmdata["editinfo"] && decodeJSON( pmdata.editinfo);
		if( editinfo){
			if( !RenderSettings.getRenderSettingData( editinfo["rsetid"])){
				editinfo.rsetid <- getDefaultRSetID();
			}
			canvas.setRenderSettingID( editinfo.rsetid);
			canvas.gridchk.setSelected( !!editinfo["gridchk"]);
			canvas.bndchk.setSelected( !!editinfo["bndchk"]);
			canvas.bonechk.setSelected( !!editinfo["bonechk"]);
			canvas.updateChecks();
		}else{
			local rsetid = getDefaultRSetID();
			canvas.setRenderSettingID( rsetid);
		}

		selectMesh( meshAt( 0));
	}

	function meshAt( idx){
		//	meshtreeには { pmt, mtls, pms, node3dmap } が入ってる。
		local pm = canvas.sk3d.meshtree.pms[idx];
		return pm;
	}

	function selectMesh( pm){
		canvas.selectMesh( pm);
		rightpanel.selectMesh( pm);
	}

	function getDefaultRSetID(){
		return "pbr_fw";
		local pmispbr = false;
		local ma = canvas.sk3d.getMaterials();
		foreach( m in ma){
			if( m.isPBR()){ pmispbr = true; break; }
		}
		return pmispbr ? "pbr_fw" : "legacy";
	}

	function pmToPMT( pmres){
		local loader = PolygonMeshLoader( pmres);
		loader.load();
		local pm = loader.mesh;
		//
		local pmt = PolygonMeshTree();
		local texmap = {};
		local pmfaces = [];
		//	textures, materials
		pmt.materials = [];
		pmt.textures = [];
		foreach( i, f in pm.face){
			local msrc = MaterialSource();
			foreach( fid in MaterialSource.fids){
				msrc[fid] = f.m[fid];
			}
			msrc.tec = f.m.tec.name;
			for( local j = 0; j < 4; j ++){
				local fid= "tex"..j, tex = f.m[fid];
				if( !tex) continue;
				local res = realref( tex.ref);	//	Resource
				local ti = texmap[res];
				if( ti == undefined){
					local ts = TextureSource();
					ts.name = res.name;
					ts.path = res.path;
					ti = length( pmt.textures);
					pmt.textures .. ts;
					texmap[res] <- ti;
				}
				msrc[fid] = ti;
			}
			pmt.materials .. msrc;
			//
			local fsrc = PolygonFaceSource();
			fsrc.idx = f.idx;
			fsrc.idxoffs = f.offs;
			fsrc.idxlen = f.len;
			fsrc.mode = f.mode;
			fsrc.vtxoffs = f.voffs;
			fsrc.matid = i;
			pmfaces .. fsrc;
		}
		//	mesh
		local pmsrc = PolygonMeshSource();
		pmsrc.name = pmres.name;
		pmsrc.vtx = pm.vtx;
		pmsrc.face = pmfaces;
		pmsrc.motion = pm.motion;
		pmsrc.shapekeys = pm.shapekeys;
		pmsrc.bnd = pm.bnd;
		pmsrc.pivot = pm.pivot;
		pmsrc.wmapname = pm.wmapname;
		//	node
		local node = PolygonMeshNode();
		node.id = 0;
		node.meshid = 0;
		node.tf = Transform();
		//
		pmt.meshes = [pmsrc];
		pmt.nodes = [node];
		pmt.res = pmres;
		pmt.ref = loader.data;
		return pmt;
	}

	function setPolygonMeshTree( pmt){
		canvas.setPolygonMeshTree( pmt);
		rightpanel.setPolygonMeshTree( pmt);
	}
	
	function rootevent( e){
		switch( e.id){
		case SCREEN_RESIZED:
			break;
		}
	}

	//	.pm以外(glTF等)は読み込み専用のためundo/redo/saveは何もしない
	function execMenu( m){
		printf( "PMEditor execMenu %S\n", encodeJSON( m));
		switch( m["uid"]){
		case "menu_edit_undo":
			op.undo();
			::skstudio.updateChangeFile( this);
			break;
		case "menu_edit_redo":
			op.redo();
			::skstudio.updateChangeFile( this);
			break;
		case "menu_file_save":
			if( res.name.endsWith( ".pm")){
				savePM();
			}else{
				savePMT();
			}
			op.markSaved();
			::skstudio.fileview.refreshDir( res.path);
			::skstudio.updateChangeFile( this);
			break;
		}
		return false;
	}

	function timeevent( e){
		canvas.pm3d.anime( e.actioncmd, e.actioncmd, 1.0, 0, 0.006);
	}

	function savePM(){
		local pm = meshAt( 0);
		local sb = StringBuffer();
		encodePM( pm, pmt.ref, sb);
		//
		local s = string( sb);
		printf("%S\n", s);		
		
		local bb = ByteBuffer();
		bb.putText( s);
		bb.pos = 0;
		// pm.res.file.save( bb);
		// postNotifyEvent( sprintf( ".pm saved - %S", pm.res.file.path));
	}

	function getEditInfo(){
		return {
			rsetid = canvas.view.renderer.env.id,
			gridchk = canvas.gridchk.isSelected(),
			bndchk = canvas.bndchk.isSelected(),
			bonechk = canvas.bonechk.isSelected(),
		}
	}
	
	///////////////////////////////////////////////////////////////////////
	//	encode PM

	static blendname = ["SK_OFF","SK_MIX","SK_PMAMIX","SK_ADD","SK_MULT","SK_MIXADD"]
	static testname  = ["SK_OFF","SK_LESS","SK_LEQUAL","SK_GREATER","SK_GEQUAL","SK_EQUAL","SK_NOTEQUAL","SK_ALWAYS","SK_NEVER"]
	static cullname  = ["SK_OFF","SK_CW","SK_CCW"]
	
	function _texsrc( res, tex){
		local ts = tex.ref;		//	TextureSource
		if( ts){
			local t = {};
			if( ts.data){
				t.data64 <- encodeBASE64( ts.data);
			}else
			if( ts.path){
				t.path <- ts.path;
			}
			return encodeJSON( t);
		}else{
			return "null";
		}
	}
	
	function encodePM( pm, pmdata, sb=null){
		local sb = sb||(#StringBuffer()).clear();
		sb.printf( "///  PolygonMesh written by SKStudio.\n/// \n")
		sb.printf( "return {\n")
		sb.printf( "editinfo = \"%S\"\n", encodeESC( encodeJSON( getEditInfo())));
		if( pmdata["model64"]){
			sb.printf( "model64 = \"%S\"\n", pmdata.model64);
		}else{
			sb.printf( "modeldata = \"%S\"\n", pmdata.modeldata);
		}
		if( pmdata["motion64"]){
			sb.printf( "motion64 = \"%S\"\n", pmdata.motion64);
		}else
		if( pmdata["motiondata"]){
			sb.printf( "motiondata = \"%S\"\n", pmdata.motiondata);
		}
		sb.printf( "bnd = [%f,%f,%f,%f,%f,%f]\n", pm.bnd.x, pm.bnd.y, pm.bnd.z, pm.bnd.r, pm.bnd.s, pm.bnd.t);
		if( pm.shapesets){
			sb.printf( "\nshapesets = %S\n", encodeJSON( pm.shapesets));
		}
		if( pm.rbdataset){
			sb.printf( "\nrbdataset = [\n");
			foreach( rb in pm.rbdataset){
				local t = rb.writeJSON();
				sb.printf( "\t%S,\n", encodeJSON( t));
			}
			sb.printf( "]\n");
		}
		sb.printf( "\nmaterial = [\n");
		foreach( i, f in pm.face){
			encodeMtl( f.m, sb);
		}
		sb.printf("]\n}\n");
		return string( sb);
	}

	function encodeMtl( m, sb){
		local m0 = #Material();		//	基準マテリアル
		//	basic param
		sb.printf( "\t{\n")
		sb.printf( "\t\tname = \"%S\"\n" , m.name)
		sb.printf( "\t\ttec = \"%S\"\n" , m.tec.name)
		if( m.tec.tag.contains( "pbr")){
			sb.printf( "\t\tmtype = %d\n" , m.mtype)
			sb.printf( "\t\tbasecol = 0x%08X\n" , m.basecol)
			sb.printf( "\t\trough = %f\n" , m.rough)
			sb.printf( "\t\tmetal = %f\n" , m.metal)
			sb.printf( "\t\tmparam = 0x%08X\n" , m.mparam)
			sb.printf( "\t\ttexmap = 0x%08X\n" , m.texmap)
		}else{
			sb.printf( "\t\tKa = 0x%08X\n" , m.Ka)
			sb.printf( "\t\tKd = 0x%08X\n" , m.Kd)
			sb.printf( "\t\tKs = 0x%08X\n" , m.Ks)
			sb.printf( "\t\tKe = 0x%08X\n" , m.Ke)
			sb.printf( "\t\tshiness = %f\n" , m.shiness)
		}
		if( m.blend) sb.printf( "\t\tblend = %S\n" , blendname[m.blend])
		if( m.depthtest != m0.depthtest) sb.printf( "\t\tdepthtest = %S\n" , testname[m.depthtest])
		if( m.depthmask != m0.depthmask) sb.printf( "\t\tdepthmask = %S\n", m.depthmask)
		if( m.alphatest) sb.printf( "\t\talphatest = %S\n" , testname[m.alphatest])
		if( m.cullface != m0.cullface) sb.printf( "\t\tcullface = %S\n" , cullname[m.cullface])
		//	texture
		if( m.tex0) sb.printf( "\t\ttexture0 = %S\n" , _texsrc( res, m.tex0))
		if( m.tex1) sb.printf( "\t\ttexture1 = %S\n" , _texsrc( res, m.tex1))
		if( m.tex2) sb.printf( "\t\ttexture2 = %S\n" , _texsrc( res, m.tex2))
		if( m.tex3) sb.printf( "\t\ttexture3 = %S\n" , _texsrc( res, m.tex3))
		if( m.uvbits) sb.printf( "\t\tuvbits = %d\n" , m.uvbits)
		if( m.texw0 != 1.0) sb.printf( "\t\ttexw0 = %f\n" , m.texw0)
		if( m.texw1 != 1.0) sb.printf( "\t\ttexw1 = %f\n" , m.texw1)
		if( m.texw2 != 1.0) sb.printf( "\t\ttexw2 = %f\n" , m.texw2)
		if( m.texw3 != 1.0) sb.printf( "\t\ttexw3 = %f\n" , m.texw3)
		if( m.visiblemask != DEFAULT_VISIBLEMASK) sb.printf( "\t\tvisiblemask = 0x%x\n", m.visiblemask)
		sb.printf( "\t}\n");
	}
}


class PMRightPanel
{
	editor = null;
	view = null;
	body = null;

	tabs = null;
	curpanel = null;

	mtlpanel = null;			//	PMMaterialPanel
	partspanel = null;			//	PMPartsPanel
	shapepanel = null;			//	PMShapePanel
	
	pmselect = null;			//	MenuBehavior
	
	constructor( v, e){
		view = v;
		body = v.findChild( "body");
		editor = e;
		tabs = TabsBehavior( v.findChild( "tabs"), ["Material","Anime","Bones","Shapes"]);
		//	panels
		mtlpanel = PMMaterialPanel( ::loadSKView( "/skstudio/ui/pmeditor/pmmtl.ui"), editor);
		partspanel = PMPartsPanel( ::loadSKView( "/skstudio/ui/pmeditor/pmparts.ui"), editor);
		body.addChild( mtlpanel.view);
		
		tabs.listview.addEventListener( ACTION_EVENT, tabevent);

		pmselect = MenuBehavior( v.findChild( "pmselect"));
		pmselect.view.addEventListener( ACTION_EVENT, pmselectevent);
	}

	function setPolygonMeshTree( pmt){
		pmselect.setMenu( pmt.meshes.map( @( m, i)+{ lbl=m.name, val=m, icon="\ue86b", }));
	}

	function selectMesh( pm){
		mtlpanel.setPM( pm);
		partspanel.setPM( pm);
	}

	function pmselectevent( e){
		e.consume();
		local ms = e.actioncmd.val;
		local pm = editor.canvas.sk3d.meshtree.pms.find( @( pm) pm.ref == ms);
		// printf( "PMMMMMMMMMMMMMMMMMMMMMMMMMMM %S %S %S\n", ms, encodeJSON( e.actioncmd), pm);
		editor.selectMesh( pm);
	}

	function tabevent( e){
		e.consume();
		body.clearChildren();
		local pnl = null;
		switch( e.actioncmd){
		case 0:	pnl = mtlpanel.view; break;
		case 1: 
		case 2:	pnl = partspanel.view; break;
		case 3:
		}
		if( !pnl) return;
		pnl.stretchSize( body.bnd.w, body.bnd.h);
		body.addChild( pnl);
	}
}

/////////////////////////////////////////////////////////////////////////////
//	register SKStudio

skstudio.registerEditor( {
	uid = "editor_pm",
	matches = @( path){ return path.endsWith( ".pm") || path.endsWith( ".glb") || path.endsWith( ".gltf"); }
	createEditor = PMEditor.createEditor,
});
