import PropertyType;
import SKViewPropertyID;

local shapelist = [
	{ lbl="BOX", icon="\ue3e0", val=SK_SHAPE_BOX },
	{ lbl="SPHERE", icon="\ue836", val=SK_SHAPE_SPHERE },
	{ lbl="CAPSULE", icon="\ue0d4", val=SK_SHAPE_CAPSULE },
	{ lbl="CYLINDER", icon="\ue71c", val=SK_SHAPE_CYLINDER },
];

local shapeidlist = [SK_SHAPE_BOX,SK_SHAPE_SPHERE,SK_SHAPE_CAPSULE,SK_SHAPE_CYLINDER];

//	on/off
local props1 = [
	{ pid="phys",	lbl="Physical Bone",	type=BOOL, cnt="cnt1.ui", refresh=3, custom=true},
];

//	group/mask, shapes, dynamic
local props2 = [
	{ pid="collisiongroup",	lbl="Col Group",	type=BIT8 },
	{ pid="collisionmask",	lbl="Col Mask",	type=BIT8 },
	{ pid="shapesel",		lbl="Shapes",		type=3415, cnt="cnt1.ui", minlen=1, newicon="\ue3e0", refresh=1},
	{ pid="shapetype",		lbl="Type",		type=LIST, list=shapelist},
	{ pid="shapesize",		lbl="Size",		type=VEC3, range=(0.01, 10.0), q=100 },
	{ pid="shapepos",		lbl="Position",	type=VEC3, range=(-10.0, 10.0), q=100 },
	{ pid="shaperot",		lbl="Rotation",	type=VEC3, range=(-360, 360), },
	{ pid="dynamic",			lbl="Physical Type",	type=LIST, cnt="cnt1.ui", list=["0:KINEMATIC","1:DYNAMIC"], refresh=3},
];

//	mass, constraint select
local props3 = [
	{ pid="mass",			lbl="Mass",		type=SCALAR, range=(0.001, 10.0), q=1000 },
	{ pid="angulardamp",		lbl="Angular Damp",	type=SCALAR, range=( 0.0, 2.0), q=1000 },
	{ pid="lineardamp",		lbl="Linear Damp",	type=SCALAR, range=( 0.0, 2.0), q=1000 },
	{ pid="constsel",		lbl="Constraints",	type=3415, cnt="cnt1.ui"},
];

//	constraint params
local props4 = [
	{ pid="consttarget",		lbl="Target",		type=3416, list=@( pl, val) ::skstudio.editor.rightpanel.partspanel.constraintList( val) },
	{ pid="constangular",	lbl="Angular Limit",	type=3417, range=(-180, 180), q=1, cnt="cnt5.ui" },
	{ pid="constlinear",		lbl="Linear Limit",	type=3417, range=(-10, 10), q=100, cnt="cnt5.ui" },
];

class PropertyBehaviors.Sel4 extends PropertyBehavior
{
	static proptype = 3415;
	static uipath = "/skstudio/ui/pmeditor/prop_sel4.ui"
	static deficons = ["\ue400","\ue401","\ue3fb","\ue3fd"];

	chk = null;

	selidx = 0; len = 1;

	function init(){
		chk = [];
		for( local l = 0;l < 4;l ++){
			chk .. view.findChild( "chk"..l);
			chk[l].setEnabled( false);
		}
	}

	function getParam(){
		return { idx = selidx, len = len };
	}
	
	function setParam( v){
		selidx = v.idx; len = v.len;
		foreach( i, v in chk){
			v.setEnabled( i < len);
			v.setSelected( i == selidx);
		}
		foreach( i, c in chk){
			local ic = (v["icons"][i] || (c.enabled ? deficons[i] : "\ue835"));
			c.setValue( "icon", ic);
		}
	}

	function sel( idx){
		foreach( i, v in chk) v.setSelected( i==idx);
		selidx = idx;
	}
	
	function paramevent( e){
		switch( e.src["name"]){
		case "addbtn":
			postActionEvent( true, "add");
			break;
		case "delbtn":
			postActionEvent( true, "del");
			break;
		default:
			sel( chk.indexOf( e.src));
			postActionEvent( true);
			break;
		}
	}
}

class PropertyBehaviors.ListPick extends PropertyBehaviors.List
{
	static proptype = 3416;
	static uipath = "/skstudio/ui/pmeditor/prop_listpick.ui"
}

class PropertyBehaviors.Constraint extends PropertyBehavior
{
	static proptype = 3417;
	static uipath = "/skstudio/ui/pmeditor/prop_const.ui"

	ulim = null;
	dlim = null;
	spchk = null;
	damp = null;
	stiff = null;

	function init(){
		ulim = _makenum3( "ulim", prop.range, prop.q);
		dlim = _makenum3( "dlim", prop.range, prop.q);
		damp = _makenum3( "damp", #(0,10), 100);
		stiff = _makenum3( "stiff", #(0,10), 100);
		spchk = [];
		for( local l = 0;l < 3;l ++) spchk .. view.findChild( "chk"..l);
	}

	function _makenum3( n, r, q){
		local a = [], p = view.findChild( n);
		for( local l = 0;l < 3;l ++){
			local v = NumInputBehavior( p.findChild( "val"..l));
			v.setRange( r[0], r[1], q);
			a .. v;
		}
		return a;
	}

	function _setnum3( n3, v3){
		foreach( i, n in n3){ n.setValue( v3[i]); }
	}

	function _getnum3( n3){
		return ( n3[0].getValue(), n3[1].getValue(), n3[2].getValue());
	}

	function getParam(){
		return {
			ulim = _getnum3( ulim)
			dlim = _getnum3( dlim)
			damp = _getnum3( damp)
			stiff = _getnum3( stiff)
			spchk = (int( spchk[0].isSelected()),int( spchk[1].isSelected()),int( spchk[2].isSelected()))
		}
	}

	function setParam( v){
		_setnum3( ulim, v.ulim);
		_setnum3( dlim, v.dlim);
		_setnum3( damp, v.damp);
		_setnum3( stiff, v.stiff);
		foreach( i, c in spchk) c.setSelected( !!v.spchk[i]);
	}
	
	function paramevent( e){
		if( e.id == VALUE_CHANGED) return;
		local n = e.src["name"];
		if( n == "lockbtn" || n == "freebtn"){
			cnt.postActionEvent( {prop=prop, val=null, cmd=n, cmdarg=null, tween=false, src=e.src });
		}else{
			postActionEvent( true);
		}
	}
}

class PMPartsPanel
{
	editor = null;
	view = null;

	partstree = null;		//	ListBehavior
	proplist = null;		//	GPUIListView

	pm = null;				//	Current mesh
	
	//	selection
	// selparts = null;
	// selrbdata = null;
	// selshape = null;
	// selcons = null;

	sel = null;				//	{ pm, parts }
	
	constructor( v, e){
		view = v;
		editor = e;
		partstree = TreeBehavior( v.findChild( "partstree"));
		partstree.listview.addEventListener( ITEM_EVENT, partstreeevent);
		partstree.setviewfunc = @( la, v, i){
			defaultsetview( la, v, i);
			local tv = v.findChild( "type"), rb = i.pm.rbdataset[i.parts.name];
			if( rb){
				tv.setVisible( true);
				tv.setText( rb.dynamic ? "\ue037" : "\ue047");
			}else{
				tv.setVisible( false);
			}
			v.pickable = false;
		}
		proplist = PropertyListBehavior( v.findChild( "proplist"));
		proplist.listview.addEventListener( ACTION_EVENT, propevent);
		proplist.listview.addEventListener( ITEM_EVENT, propevent);
		proplist.ref = e;
	}
	
	function setPM( p){
		pm = p;
		local pt = buildPartsTree( p, p.motion);
		partstree.setItemTree( pt);
		partstree.expandAll();
		partstree.scrollIndexToVisible( 0);
		partstree.setSelectedIndex( 0);
		selectParts( pt.children[0] || null);
	}

	function _rbdata( sel){
		return sel.pm.rbdataset[ sel.parts["parts"]["name"]] || null;
	}

	function selectParts( pb){
		sel = {
			pm = pm;
			parts = pb;
		};
		local rbdata = _rbdata( sel);
		if( rbdata){
			if( !rbdata.ref) rbdata.ref = { shape = null; cons = null; };
			//
			if( length( rbdata.shapes)){
				rbdata.ref.shape = rbdata.shapes[0];
			}
			if( length( rbdata.constraints)){
				rbdata.ref.cons = rbdata.constraints[0];
			}
		}
		assignProperties();
		editor.canvas.selectBoneParts( pb["parts"]);
	}

	function selectBone( b){
		local bp = b.parts;
		local i = partstree.items.findi( @( v){
			return v.parts == bp;
		});
		if( i >= 0){
			partstree.setSelectedIndex( i);
			partstree.scrollIndexToVisible( i);
		}
	}

	//	
	function buildPartsTree( pm, mot){
		local rootlist = [];
		local root = { lbl = "root"; icon = null; children = rootlist; isdir = true; parts = null; parent = null; pblist = [] };
		if( !mot) return root;
		local pblist = root.pblist;
		//
		foreach( bp in mot.parts){
			local pb = {
				pm = pm;
				icon = "\uea3b";
				lbl = bp.name;
				parts = bp;
				parent = root;
				children = null;
				isdir = false;
			};
			if( bp.parentid < 0){
				rootlist .. pb;
			}else
			foreach( _pb in pblist){
				if( _pb.parts.id == bp.parentid){
					pb.parent = _pb;
					if( _pb.children) _pb.children .. pb; else { _pb.children = [pb]; _pb.isdir = true; }
					break;
				}
			}
			pblist..pb;
		}
		return root;
	}
	
	function assignProperties(){
		local props = [];
		if( !sel["parts"]) return proplist.bindProperties( props);
		props ... props1;
		local rbdata = _rbdata( sel);
		if( rbdata){
			props ... props2;
			if( rbdata.dynamic){
				props ... props3;
				if( rbdata.ref.cons){
					props ... props4;
				}
			}
		}
		proplist.bindProperties( props);
		local prms = {};
		foreach( p in props){
			local v = getPartsParam( sel, p.pid);
			if( v != undefined) prms[p.pid] <- v;
		}
		proplist.setParameters( prms);
	}

	function constraintList( val){
		local selname = sel.parts["parts"]["name"];
		local rbdataset = pm.rbdataset;
		return partstree.itemtree.pblist.map( @( v){
			local n = v.parts["name"], rbdata = rbdataset[n];
			if( !rbdata) return undefined;
			return { lbl=n, val=n, icon=v["icon"], disable=(n==selname)};
		});
	}
	
	static function vtoa( v){ return (v.x,v.y,v.z); }

	function getPartsParam( sel, pid){
		local rbdata = _rbdata( sel), rbref = rbdata["ref"];
		switch( pid){
		case "phys": return !!rbdata;
		case "collisiongroup": case "collisionmask": case "collisionmask":
			return rbdata[pid];
		case "shapesel":
		{
			local v = { idx=rbdata.shapes.indexOf( rbref.shape), len=length( rbdata.shapes), icons=[]};
			foreach( s in rbdata.shapes){
				local i = shapeidlist.indexOf( s.shapetype);
				v.icons .. shapelist[i].icon;
			}
			return v;
		}
		case "shapetype": return rbref.shape.shapetype;
		case "shapesize": return vtoa( rbref.shape.size);
		case "shapepos": return vtoa( rbref.shape.pos);
		case "shaperot": return vtoa( rbref.shape.rot * Math.RTOD);
		case "dynamic": return rbdata.dynamic ? 1 : 0;
		case "mass": return rbdata.mass;
		case "angulardamp": return rbdata.angulardamp;
		case "lineardamp": return rbdata.lineardamp;
		case "consttarget":
			return rbref.cons["pairpartsname"] || null;
		case "constsel":
			return rbref.cons ? { idx=rbdata.constraints.indexOf( rbref.cons), len=length( rbdata.constraints)} : {idx=-1,len=0};
		case "constangular":
			if( !rbref.cons) return undefined;
			return _getconstval( rbref.cons, 6, 9);
		case "constlinear":
			if( !rbref.cons) return undefined;
			return _getconstval( rbref.cons, 0, 0);
		}
		return undefined;
	}

	function _getconstval( cons, l, s){
		local lim = cons.limit, sp = cons.spring;
		return {
			dlim = (lim[l], lim[l+1], lim[l+2]), ulim = (lim[l+3], lim[l+4], lim[l+5]),
			spchk = (sp[s  ], sp[s+3], sp[s+6]),
			stiff = (sp[s+1], sp[s+4], sp[s+7]),
			damp  = (sp[s+2], sp[s+5], sp[s+8]),
		};
	}
	
	function setPartsParam( sel, pid, val){
		local rbdata = _rbdata( sel), rbref = rbdata["ref"];
		switch( pid){
		case "shapesel":
			local s = rbdata.shapes[val.idx];
			if( s){ rbref.shape = s; }
			return true;
		case "shapetype":
			rbref.shape.shapetype = val;
			proplist.setParameters( {shapesel=getPartsParam( sel, "shapesel")});
			return true;
		case "shapesize":
			rbref.shape.size = Vector3D( val);
			return true;
		case "shapepos":
			rbref.shape.pos = Vector3D( val);
			return true;
		case "shaperot":
			rbref.shape.rot = Vector3D( val).scale( Math.DTOR);
			return true;
		case "dynamic":
			rbdata.dynamic = !!val;
			partstree.refreshItems();
			assignProperties();
			return true;
		case "mass":
			rbdata.mass = val;
			return true;
		case "angulardamp":
			rbdata.angulardamp = val;
			return true;
		case "lineardamp":
			rbdata.lineardamp = val;
			return true;
		case "constangular":
			if( !rbref.cons) return false;
			_setconstval( rbref.cons, val, 6, 9);
			return true;
		case "constlinear":
			if( !rbref.cons) return false;
			_setconstval( rbref.cons, val, 0, 0);
			return true;
		case "collisiongroup": case "collisionmask": case "collisionmask":
			rbdata[pid] = val;
			return true;
		}
	}

	function _setconstval( cons, v, l, s){
		local lim = cons.limit, sp = cons.spring;
		if( l >= 0){
			lim[l  ] = v.dlim[0]; lim[l+1] = v.dlim[1]; lim[l+2] = v.dlim[2];
			lim[l+3] = v.ulim[0]; lim[l+4] = v.ulim[1]; lim[l+5] = v.ulim[2];
		}
		//
		if( s >= 0){
			sp[s  ] = v.spchk[0]; sp[s+3] = v.spchk[1]; sp[s+6] = v.spchk[2];
			sp[s+1] = v.stiff[0]; sp[s+4] = v.stiff[1]; sp[s+7] = v.stiff[2];
			sp[s+2] = v.damp [0]; sp[s+5] = v.damp [1]; sp[s+8] = v.damp [2];
		}
	}

	function actionPartsParam( fid, val, cmd){
		local rbdata = _rbdata( sel), rbref = rbdata["ref"], self = this;
		switch( fid){
		case "phys":
		{
			local oldval = !!rbdata, _sel = clone sel, _rbdata = RigidBodyData();
			local redo = [@(){ self.setPhysicsOn( _sel, val, _rbdata); self.assignProperties(); self.partstree.refreshItems(); }];
			local undo = [@(){ self.setPhysicsOn( _sel, oldval, _rbdata); self.assignProperties(); self.partstree.refreshItems(); }];
			editor.submitOp( redo, undo);
			return true;
		}
		case "shapesel":
			switch( cmd){
			case "add": 
				if( length( rbdata.shapes) < 4){
					local shp = _newrbshape();
					local redo = [@(){ rbref.shape = shp; rbdata.shapes .. shp; self.assignProperties(); }];
					local undo = [@(){ rbdata.shapes.pop(); rbref.shape = rbdata.shapes.last(); self.assignProperties(); }];
					editor.submitOp( redo, undo);
					return true;
				}
				break;
			case "del": 
				if( length( rbdata.shapes) > 1){
					local i = val.idx, shp = rbdata.shapes[i];
					local redo = [@(){ delete rbdata.shapes[i]; rbref.shape = rbdata.shapes[i] || rbdata.shapes[i-1]; self.assignProperties(); }];
					local undo = [@(){ rbdata.shapes[i] <- shp; rbref.shape = shp; self.assignProperties(); }];
					editor.submitOp( redo, undo);
				}
				break;
			}
			return true;
		case "constsel":
			switch( cmd){
			case "add":
				if( length( rbdata.constraints) < 4){
					if( !rbdata.constraints) rbdata.constraints = [];
					local cons = _newrbconst( sel.parts);
					if( cons){
						local redo = [@(){ rbref.cons = cons; rbdata.constraints .. cons; self.assignProperties(); }];
						local undo = [@(){ rbdata.constraints.pop(); rbref.cons = rbdata.constraints.last(); printf( "constr? %S\n", rbref.cons); self.assignProperties(); }];
						editor.submitOp( redo, undo);
						return true;
					}else{
						Popups.showError( "$T.editor_pm_error_constraint");
					}
				}
				break;
			case "del": 
				if( length( rbdata.constraints)){
					local i = val.idx, cons = rbdata.constraints[i];
					local redo = [@(){ delete rbdata.constraints[i]; rbref.cons = rbdata.constraints[i] || rbdata.constraints[i-1] || null; self.assignProperties(); }];
					local undo = [@(){ rbdata.constraints[i] <- cons; rbref.cons = cons; self.assignProperties(); }];
					editor.submitOp( redo, undo);
				}
				break;
			}
			return true;
		case "constangular":
		case "constlinear":
			printf( "constangular/constlinear cmd: %S %S\n", fid, cmd);
			local _setvalmap = #{
				"lockbtn": { dlim=[0.0,0.0,0.0] ulim=[0.0,0.0,0.0], },
				"freebtn": { dlim=[-180.0,-180.0,-180.0] ulim=[180.0,180.0,180.0], },
			};
			local cons = rbref.cons, setval = _setvalmap[cmd];
			if( setval){
				local l = fid=="constangular"?6:0, oldval = _getconstval( cons, l, 0);
				local redo = [@(){ self._setconstval( cons, setval, l, -1); self.assignProperties(); }];
				local undo = [@(){ self._setconstval( cons, oldval, l, -1); self.assignProperties(); }];
				editor.submitOp( redo, undo);
			}
			return true;
		}
	}

	function setPhysicsOn( sel, b, rbdata){
		local name = sel.parts["parts"]["name"];
		if( !b){
			delete sel.pm.rbdataset[name];
		}else
		if( !_rbdata( sel)){
			//	デフォルトのRigidBodyDataを設定。rbdataは参照を共有できるように外部から渡す
			if( !sel.pm.rbdataset) sel.pm.rbdataset = { [name]=rbdata}; else sel.pm.rbdataset[name] <- rbdata;
			rbdata.partsname = name;
			if( !rbdata.ref) rbdata.ref = { shape=null, cons=null }; else rbdata.ref.shape = rbdata.ref.cons = null;	//	refも共有
			local shp = RigidBodyShapeData();
			shp.shapetype = SK_SHAPE_BOX;
			shp.size = Vector3D( 0.1, 0.1, 0.1);
			shp.pos = Vector3D( 0.0, 0.0, 0.0);
			shp.rot = Vector3D( 0.0, 0.0, 0.0);
			rbdata.ref.shape = _newrbshape();
			rbdata.shapes = [rbdata.ref.shape];
			rbdata.ref.cons = null;
		}
	}

	function _newrbshape(){
		local shp = RigidBodyShapeData();
		shp.shapetype = SK_SHAPE_BOX;
		shp.size = Vector3D( 0.1, 0.1, 0.1);
		shp.pos = Vector3D( 0.0, 0.0, 0.0);
		shp.rot = Vector3D( 0.0, 0.0, 0.0);
		return shp;
	}

	function _newrbconst( pb){
		//	parent rigid body!
		local rbdataset = pb.pm.rbdataset;
		local mot = pb.pm.motion;
		local p = pb.parent;
		while( p){
			if( rbdataset[p["parts"]["name"]]) break;
			p = p.parent;
		}
		if( !p){
			return null;
		}
		local cons = RigidBodyConstraintData();
		cons.pairpartsname = p.parts.name;
		cons.limit = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
		cons.spring = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0, 0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
		return cons;
	}

	function propevent( e){
		local cmd = e.actioncmd, prop = cmd["prop"], pid = prop["pid"];
		if( cmd.cmd=="prop" && !prop["custom"]){
			local refresh = prop["refresh"]|0, _sel = clone sel;
			local oldval = getPartsParam( _sel, pid), self = this;
			local _setval( val){
				self.setPartsParam( _sel, pid, val);
				self.editor.canvas.resetRigidBody();
				if( _sel.pm == self.pm){
					if( refresh & 1) self.assignProperties();
					else self.proplist.setParameters( { [pid]=val, });
					if( refresh & 2) self.partstree.refreshItems();
				}
			}
			local redo = [@() _setval( cmd.val)];
			local undo = [@() _setval( oldval)];
			editor.submitOp( redo, undo);
		}else{
			if( actionPartsParam( pid, cmd["val"], cmd.cmd)){
				editor.canvas.resetRigidBody();
			}
		}
	}

	function partstreeevent( e){
		e.consume();
		switch( e.id){
		case ITEM_SELECTED:
			selectParts( e.actioncmd);
			break;
		case ITEM_HOVER:
			editor.canvas.mouseonBoneParts( e.actioncmd["parts"]);
			break;
		}
	}
}
